### ISSUE TITLE
[Proposal] Allow empty line after function signature

### ISSUE THREAD

**Issue by ldiqual** [siteline/eslint-config-siteline#8]
Current style:

```
function foo (
  param
  param) {
  code
  code
}
```

It look like `code` is part of the function signature.

Proposal:

```
function foo (
  param
  param) {

  code
  code
}
```

**Comment by joelpoloney** [comment]
Hm... not quite sure exactly how we'd allow for this. This is the error I get when I try to add an empty line:
```
/Users/joel/Code/timber/packages/server/src/resolvers/pay-app-attachment.ts
  16:60  error  Block must not be padded by blank lines  padded-blocks

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```
This is the rule https://eslint.org/docs/rules/padded-blocks but there's no option to allow this as optional. It's either required to have both lines (beginning/end) or you can't have it at all 😢

**Comment by ldiqual** [comment]
@joelpoloney Since arnav is already modifying rules, can we tackle this one? This is the one that gets me the most – along with the 100char limit. We can just disable the rule – it'll allow 0 or 1 padded line, and 2 empty lines will be caught by another rule I believe.

**Comment by joelpoloney** [comment]
Yeah, this is fine if we want to allow it. The line length I feel strongly about keeping in some capacity, but do you think we should increase it? If so, to what?

**Comment by arnmishra** [comment]
@ldiqual I was reading this thread - not sure if its relevant anymore since prettier seems to enforce this as well (if I add an empty line after a function signature, it deletes it automatically) unless we want to explore deleting on both.

I also find line length useful to help with code readability during reviews - we had an 80char limit at Rubrik iirc which helped prevent a single line from wrapping on our code review system

**Comment by ldiqual** [comment]
Prettier will take care of this – removing eslint's focus on code style
